{"version":3,"file":"invalid-argument-exception.js","sourceRoot":"","sources":["../src/invalid-argument-exception.ts"],"names":[],"mappings":";;;;;;;;;;;;AAAA,yCAAoC;AACpC,iBAAe;AAEf;IAAuC,4CAAS;IAI5C,kCAAmB,OAAe,EAAE,cAA0B;QAA9D,iBAQC;QANG,EAAE,CAAC,CAAC,OAAO,IAAI,IAAI,IAAI,OAAO,CAAC,mBAAmB,EAAE,CAAC;YACjD,OAAO,GAAG,WAAW,CAAC;QAE1B,IAAM,OAAO,GAAG,2BAA2B,CAAC,MAAM,CAAC,OAAO,CAAC,CAAC;QAE5D,QAAA,kBAAM,OAAO,EAAE,cAAc,CAAC,SAAC;;IACnC,CAAC;IACL,+BAAC;AAAD,CAAC,AAbD,CAAuC,mBAAS,GAa/C;AAED,kBAAe,wBAAwB,CAAC","sourcesContent":["import Exception from \"./exception\";\nimport \"n-ext\";\n    \nclass InvalidArgumentException extends Exception\n{\n    public constructor(argName: string);\n    public constructor(argName: string, innerException: Exception);\n    public constructor(argName: string, innerException?: Exception)\n    {\n        if (argName == null || argName.isEmptyOrWhiteSpace())\n            argName = \"<UNKNOWN>\";\n\n        const message = \"Argument '{0}' is invalid\".format(argName);\n\n        super(message, innerException);\n    }\n}\n\nexport default InvalidArgumentException;"]}